"""Financial-statement contracts and deterministic normalization."""

from .akshare_provider import AkshareFinancialProvider
from .akshare_valuation import AkshareValuationReferenceProvider
from .analysis import (
    build_fundamental_snapshot,
    build_valuation_snapshot,
    derive_valuation_denominators,
    percentile_rank,
)
from .contracts import (
    CONTRACT_VERSION,
    STOCK_RESEARCH_CONTRACT_VERSION,
    AccountingStandard,
    ActionGuidance,
    CompanyEvent,
    CompanyEventEntity,
    ComparableGroup,
    EventDirection,
    FinancialLineItem,
    FinancialPeriodType,
    FinancialStatement,
    FundamentalSnapshot,
    HoldingStatus,
    InstrumentRelationship,
    MacroEvent,
    MacroTransmission,
    NormalizedFinancialStatement,
    PointInTimeProvenance,
    ResearchHorizon,
    ResearchMode,
    RiskPreference,
    StatementType,
    UserResearchPreference,
    ValuationMetric,
    ValuationSnapshot,
    normalize_amount,
    reconcile_statements,
)
from .events import build_company_events
from .guidance import build_action_guidance
from .macro import AkshareMacroProvider, build_macro_transmissions
from .normalization import (
    build_ttm_line_items,
    canonical_content_hash,
    classify_freshness,
    cumulative_to_single_quarter,
    resolve_statement_conflicts,
    select_available_statements,
)
from .provider import (
    FinancialProviderCapability,
    FinancialProviderStatus,
    FinancialStatementProvider,
    FinancialStatementQuery,
    ValuationReferenceData,
    ValuationReferenceProvider,
)
from .sec_provider import (
    SecCompanyFactsFinancialProvider,
    SecCompanyFactsHttpClient,
    SecCompanyFactsValuationReferenceProvider,
)

__all__ = [
    "CONTRACT_VERSION",
    "STOCK_RESEARCH_CONTRACT_VERSION",
    "AccountingStandard",
    "ActionGuidance",
    "AkshareFinancialProvider",
    "AkshareMacroProvider",
    "AkshareValuationReferenceProvider",
    "CompanyEvent",
    "CompanyEventEntity",
    "ComparableGroup",
    "EventDirection",
    "FinancialLineItem",
    "FinancialPeriodType",
    "FinancialProviderCapability",
    "FinancialProviderStatus",
    "FinancialStatement",
    "FinancialStatementProvider",
    "FinancialStatementQuery",
    "FundamentalSnapshot",
    "HoldingStatus",
    "InstrumentRelationship",
    "MacroEvent",
    "MacroTransmission",
    "NormalizedFinancialStatement",
    "PointInTimeProvenance",
    "ResearchHorizon",
    "ResearchMode",
    "RiskPreference",
    "SecCompanyFactsFinancialProvider",
    "SecCompanyFactsHttpClient",
    "SecCompanyFactsValuationReferenceProvider",
    "StatementType",
    "UserResearchPreference",
    "ValuationMetric",
    "ValuationReferenceData",
    "ValuationReferenceProvider",
    "ValuationSnapshot",
    "build_action_guidance",
    "build_company_events",
    "build_fundamental_snapshot",
    "build_macro_transmissions",
    "build_ttm_line_items",
    "build_valuation_snapshot",
    "canonical_content_hash",
    "classify_freshness",
    "cumulative_to_single_quarter",
    "derive_valuation_denominators",
    "normalize_amount",
    "percentile_rank",
    "reconcile_statements",
    "resolve_statement_conflicts",
    "select_available_statements",
]
